FROM mysql:8.0

# Set timezone if needed
ENV TZ=UTC

# The MySQL image will automatically create the database and user
# if you provide MYSQL_ROOT_PASSWORD, MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD

# Custom configuration can be added via the mounted volume
# ./mysql/conf:/etc/mysql/conf.d

EXPOSE 3306
